workspace: HeadphoneDAC.cywrk
project: HeadphoneDAC
version: HeadphoneDAC.cydsn/version.h
build_type: Release
psoc_creator_version: 4.4
upgrade_file: HeadphoneDAC.cydsn/CortexM3/ARM_GCC_541/Release/HeadphoneDAC.cyacd
release_files:
  - HeadphoneDAC.cydsn/CortexM3/ARM_GCC_541/Release/HeadphoneDAC.cyacd
  - HeadphoneDAC.cydsn/CortexM3/ARM_GCC_541/Release/HeadphoneDAC.hex
  - ProjectConfig.yaml
  - scripts/psoc_creator.py
  - scripts/avril.py
  - scripts/bootload.py
  - scripts/listen.py
  - requirements.txt
  - README.md

registers:
  timestamp: 2048
  enter_bootload: 16384
